{% set version = "0.1.2" %}

package:
  name: radiant-mlhub
  version: "{{ version }}"

source:
  git_url: https://github.com/radiantearth/radiant-mlhub.git
  git_rev: "v{{ version }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - mlhub=radiant_mlhub.cli:mlhub

requirements:
  host:
    - python
  run:
    - python >=3.6
    - requests >=2.25.1,<3
    - pystac >=0.5.4,<0.6
    - click >=7.1.2,<8
    - tqdm >=4.56.0,<5


test:
  commands:
    - mlhub --version
about:
  home: "https://github.com/radiantearth/radiant-mlhub"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "A Python client for Radiant MLHub"
  doc_url: https://radiant-mlhub.readthedocs.io
  dev_url: https://github.com/radiantearth/radiant-mlhub

extra:
  recipe-maintainers:
    - duckontheweb
