name: Publish Python distribution to PyPI

on:
  release:
    types:
    - published
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:

    # Only run the job for releases and PRs against main from release* branches
    if: >-
      github.event_name == 'release' ||
      (github.event_name == 'pull_request' && startswith(github.ref, 'ref/heads/release'))

    name: Build and publish Python distribution to PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution to PyPI
      # Publish to PyPi for releases
      if: (github.event_name == 'release') && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}

    - name: Publish distribution to TestPyPI
      # Publish to TestPyPi for PRs against main from release branches
      if: (github.event_name == 'pull_request') && startsWith(github.ref, 'refs/heads/release')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
        repository_url: https://test.pypi.org/legacy/
