name: Unit tests

on:

  push:

    branches:
      - main
      - dev

    paths:
      - 'radiant_mlhub/**'
      - setup.py
      - pyproject.toml
      - 'test/**'
      - '.github/workflows/run-unit-tests.yml'

  pull_request:

    branches:
      - main
      - dev

    paths:
      - 'radiant_mlhub/**'
      - setup.py
      - pyproject.toml
      - 'test/**'
      - '.github/workflows/run-unit-tests.yml'

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install linter dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8~=3.8.0 mypy~=0.790

      - name: Run flake8 and mypy
        run: |
          flake8
          mypy radiant_mlhub

  test_linux:

    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
        os:
          - ubuntu-18.04

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version }}

      # Caches the pip install directory based on the OS
      - name: Cache test dependencies (${{ matrix.os }})
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: unit-tests-${{ matrix.os }}-python${{ matrix.python-version }}-${{ hashFiles('requirements_testing.txt') }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_testing.txt

      - name: Run tests
        run: |
          pip install .
          pytest test

  test_mac_windows:

    # Only run this for PRs against main and pushes to main
    if: >-
      (github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')

    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
        os:
          - macos-10.15
          - windows-2019

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version }}

      # Caches the pip install directory based on the OS
      - name: Cache test dependencies (${{ matrix.os }})
        uses: actions/cache@v2
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: unit-tests-${{ matrix.os }}-python${{ matrix.python-version }}-${{ hashFiles('requirements_testing.txt') }}

      - name: Cache test dependencies (${{ matrix.os }})
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: unit-tests-${{ matrix.os }}-python${{ matrix.python-version }}-${{ hashFiles('requirements_testing.txt') }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_testing.txt

      - name: Run tests
        run: |
          pip install .
          pytest test